# Generated by Django 5.2.7 on 2025-10-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
