# Generated by Django 5.2.7 on 2025-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp1', '0002_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
