# Generated by Django 5.2.7 on 2025-10-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp1', '0003_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
