# Generated by Django 5.2.7 on 2025-10-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp1', '0005_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
