# Generated by Django 5.2.7 on 2025-10-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp1', '0006_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
